### PR TITLE
Clarify instructions for archive creation

### PR DESCRIPTION
**Pull request by daniel-widrick**
Readme instructions were vague and could be interpreted several ways. Have added more precise wording that assist future users/developers.

### CODE REVIEW

**Comment by daniel-widrick** [comment]
Should help resolve #12

**Comment by ghost** [comment]
This helped me to side-load the application onto my TCL Roku TV.

**Comment by JustAMan** [comment]
@daniel-widrick please base off #10 and #11

**Comment by daniel-widrick** [comment]
I think I covered the conflicting pulls while keeping the wording clear and professional.

**Review by JustAMan — APPROVED** [review]

**Pull request merged**
