### PR TITLE
Removing Emby Connect prompts from setup

### PR DESCRIPTION
**Pull request by nZambi-**
This commit removes the prompts for Emby Connect from the first-run screens, while preserving the Server Scan and the ability to Manually add a server. If the server is already running (and available on the network) it should be presented first.

### CODE REVIEW

**Comment by andrewrabert** [comment]
@nZambi- The placeholders look too good for being temporary. Can you make something uglier so people don't assume that's our final logo? :P

Yes, I'm serious. I'm working with a few graphic designers on a final logo so we shouldn't have to wait much longer.

**Comment by nZambi-** [comment]
> 
> Yes, I'm serious. I'm working with a few graphic designers on a final logo so we shouldn't have to wait much longer.

hahah   OMG! too funny... OK I'll watermark them or something...  I'll be back. 
Is there some place other than r/jellyfin or the Issues where this is being discussed (Branding that is) where I can sorta keep up? If you are working quietly That's fine, I get it...

**Comment by andrewrabert** [comment]
Logo discussion: https://github.com/jellyfin/jellyfin/issues/101

Unrelated - can you please send me an email at ar@nullsum.net? I'd like to chat about a few things.

**Comment by nZambi-** [comment]
More Obvious placeholders added...

**Comment by andrewrabert** [comment]
Mmm - very ugly, thank you!

**Pull request merged**
